KAA-443: Update REST API to cover Kaa 0.7.0 features and improvements.

diff --git a/server/common/src/sh/bin/console b/server/common/src/sh/bin/console
--- a/server/common/src/sh/bin/console
+++ b/server/common/src/sh/bin/console
@@ -14,37 +14,29 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-args=$@
+args="$*"
 argCount=$#
 
 function console()
 {
-    if [[ -z "$LIB" ]]; then
-	source config
-    fi
-
-    if [[ -z "$SERVER_NAME" ]]; then
-	export SERVER_NAME="Kaa"
+    if [ -z $SERVER_HOME ]; then
+        echo "This script can't be invoked standalone! Exiting..."
+        exit 1
     fi
 
     arguments=""
+
+    if [[ ! -z "$THRIFT_CONF" ]]; then
+       arguments="-c $THRIFT_CONF"
+    fi
+
     if [ $argCount -gt 0 ]; then
-       arguments="-e $args"
+       arguments="$arguments -e"
     else
        echo "Starting $SERVER_NAME Console"
     fi
     
-    if [[ ! -z "$THRIFT_CONF" ]]; then
-       arguments="-c $THRIFT_CONF $arguments"
-    fi
-
-    if [[ -z "$SERVER_LOG_DIR" ]]; then
-	SERVER_LOG_DIR=/tmp/$USER/kaa
-    fi
-    
-    JAVA_OPTIONS="$JAVA_OPTIONS -Dserver_log_dir=$SERVER_LOG_DIR"
-
-    java -cp "$CONF:$LIB/*" $JAVA_OPTIONS org.kaaproject.kaa.server.common.thrift.cli.client.BaseCliThriftClient $arguments
+    exec java -cp "$CONF:$LIB/*" $JAVA_OPTIONS org.kaaproject.kaa.server.common.thrift.cli.client.BaseCliThriftClient $arguments "$args"
 }
 
 
